/* Compiler - Transforms S-expressions to bytecode
 *
 * The compiler takes parsed S-expressions from the reader and generates
 * bytecode for the VM. It handles:
 * - Literal compilation (numbers, strings, keywords, etc.)
 * - Function calls with argument evaluation
 * - Special forms (if, do, def, fn, let, etc.)
 * - Lexical scoping and closure capture
 * - Tail call optimization
 *
 * Phase 5 (Simple Compiler):
 * - Basic literals and function calls
 * - Special forms: if, do, def, fn (basic)
 * - Simple symbol resolution
 *
 * Future phases:
 * - Macros and macro expansion
 * - loop/recur
 * - try/catch/finally
 * - Advanced optimizations
 */

#ifndef BEERLANG_COMPILER_H
#define BEERLANG_COMPILER_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "value.h"
#include "vector.h"
#include "hashmap.h"

/* Forward declarations */
typedef struct Compiler Compiler;
typedef struct BytecodeBuffer BytecodeBuffer;
typedef struct ConstantPool ConstantPool;
typedef struct LexicalEnv LexicalEnv;
typedef struct CompiledCode CompiledCode;
typedef struct CaptureEntry CaptureEntry;
typedef struct CaptureList CaptureList;
typedef struct RecurTarget RecurTarget;

/* Bytecode buffer - dynamic array for generated code */
struct BytecodeBuffer {
    uint8_t* code;          /* Bytecode array */
    size_t length;          /* Current length */
    size_t capacity;        /* Allocated capacity */
};

/* Constant pool - stores constant values */
struct ConstantPool {
    Value constants_vec;    /* Vector of constant values */
    Value const_map;        /* HashMap: Value -> index (deduplication) */
};

/* Lexical environment - tracks local bindings */
struct LexicalEnv {
    LexicalEnv* parent;     /* Parent environment */
    Value bindings;         /* HashMap: Symbol -> local index */
    bool is_function;       /* Function boundary? */
    int base_index;         /* Base local index for this scope */
};

/* Capture entry - one captured variable from an enclosing scope */
struct CaptureEntry {
    Value symbol;           /* The captured symbol */
    bool from_closure;      /* true = parent loads via OP_LOAD_CLOSURE */
    int parent_idx;         /* local index or closure index in parent */
};

/* Capture list - tracks all captured variables for a function being compiled */
#define MAX_CAPTURES 256
struct CaptureList {
    CaptureEntry entries[MAX_CAPTURES];
    int count;
};

/* Recur target - tracks the nearest loop or fn for recur */
struct RecurTarget {
    uint32_t jump_pc;          /* PC to jump back to (start of body) */
    int first_binding_index;   /* local index of first binding/param */
    int n_bindings;            /* number of bindings (arity check for recur) */
};

/* Compiled code result */
struct CompiledCode {
    uint8_t* bytecode;      /* Generated bytecode (owned) */
    size_t code_size;       /* Size of bytecode */
    Value constants;        /* Vector of constants (owned) */
    int n_locals;           /* Number of local variables */
    int arity;              /* Function arity (-1 for top-level) */
};

/* Compiler state */
struct Compiler {
    /* Bytecode generation */
    BytecodeBuffer* bytecode;
    ConstantPool* constants;

    /* Lexical environment */
    LexicalEnv* env;

    /* Closure tracking */
    CaptureList* captures;  /* Current fn's capture list (NULL if not in fn) */

    /* Recur target (nearest enclosing loop or fn) */
    RecurTarget* recur_target;

    /* Compilation state */
    bool in_tail_pos;       /* Currently in tail position? */
    int local_count;        /* Total locals in current function */

    /* Error tracking */
    bool error;
    char error_msg[512];
    const char* filename;
    int line;
    int column;
};

/* =================================================================
 * Compiler Lifecycle
 * ================================================================= */

/* Create a new compiler */
Compiler* compiler_new(const char* filename);

/* Free compiler resources */
void compiler_free(Compiler* c);

/* Reset compiler state (for reuse) */
void compiler_reset(Compiler* c);

/* =================================================================
 * Bytecode Buffer
 * ================================================================= */

/* Create bytecode buffer */
BytecodeBuffer* bytecode_buffer_new(void);

/* Free bytecode buffer */
void bytecode_buffer_free(BytecodeBuffer* buf);

/* Append byte to buffer */
void bytecode_emit_byte(BytecodeBuffer* buf, uint8_t byte);

/* Append uint16 to buffer (little-endian) */
void bytecode_emit_uint16(BytecodeBuffer* buf, uint16_t value);

/* Append uint32 to buffer (little-endian) */
void bytecode_emit_uint32(BytecodeBuffer* buf, uint32_t value);

/* Append int64 to buffer (little-endian) */
void bytecode_emit_int64(BytecodeBuffer* buf, int64_t value);

/* Get current bytecode offset */
size_t bytecode_current_offset(BytecodeBuffer* buf);

/* Patch uint16 at given offset (for jump resolution) */
void bytecode_patch_uint16(BytecodeBuffer* buf, size_t offset, uint16_t value);

/* Patch uint32 at given offset */
void bytecode_patch_uint32(BytecodeBuffer* buf, size_t offset, uint32_t value);

/* Patch int32 at given offset (for jump offsets) */
void bytecode_patch_int32(BytecodeBuffer* buf, size_t offset, int32_t value);

/* =================================================================
 * Constant Pool
 * ================================================================= */

/* Create constant pool */
ConstantPool* constant_pool_new(void);

/* Free constant pool */
void constant_pool_free(ConstantPool* pool);

/* Add constant to pool (with deduplication)
 * Returns index in constant pool
 */
int constant_pool_add(ConstantPool* pool, Value constant);

/* Get constant at index */
Value constant_pool_get(ConstantPool* pool, int index);

/* Get number of constants */
int constant_pool_size(ConstantPool* pool);

/* =================================================================
 * Lexical Environment
 * ================================================================= */

/* Create lexical environment */
LexicalEnv* lexical_env_new(LexicalEnv* parent, bool is_function);

/* Free lexical environment */
void lexical_env_free(LexicalEnv* env);

/* Add local binding (returns local index) */
int lexical_env_add_local(LexicalEnv* env, Value symbol);

/* Lookup local binding (returns -1 if not found) */
int lexical_env_lookup(LexicalEnv* env, Value symbol);

/* =================================================================
 * Compilation API
 * ================================================================= */

/* Compile a single expression to bytecode
 * Returns CompiledCode on success, NULL on error
 */
CompiledCode* compile(Compiler* c, Value form);

/* Compile expression (internal, updates compiler state) */
void compile_expr(Compiler* c, Value form, bool in_tail_pos);

/* Free compiled code */
void compiled_code_free(CompiledCode* code);

/* =================================================================
 * Emission Helpers
 * ================================================================= */

/* Emit opcode (no operands) */
void emit_op(Compiler* c, uint8_t opcode);

/* Emit opcode with uint16 operand */
void emit_uint16(Compiler* c, uint8_t opcode, uint16_t operand);

/* Emit opcode with uint32 operand */
void emit_uint32(Compiler* c, uint8_t opcode, uint32_t operand);

/* Emit opcode with int32 operand */
void emit_int32(Compiler* c, uint8_t opcode, int32_t operand);

/* Emit opcode with int64 operand */
void emit_int64(Compiler* c, uint8_t opcode, int64_t operand);

/* =================================================================
 * Error Handling
 * ================================================================= */

/* Report compilation error */
void compile_error(Compiler* c, const char* fmt, ...);

/* Check if compiler has error */
bool compiler_has_error(Compiler* c);

/* Get error message */
const char* compiler_error_msg(Compiler* c);

#endif /* BEERLANG_COMPILER_H */
